spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.106/weixinsell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.106
    port: 6379
#项目根路径
server:
  context-path: /weixinsell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    cn.edu.jxnu.LoggerTest: debug

#微信配置文件[公众号id,公众号密钥,开放平台id,开放平台密钥,支付商家编号,密钥,密钥路径,异步通知回调路径]
wechat:
  mpAppId: wx11959a5df106ac3a
  mpAppSecret: 47609bae088c91892f1f45f3675a30f8
  openAppId: 需要公司资质，开放平台id
  openAppSecret: 需要公司资质，开发平台密钥
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85 
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://weixinsell.nat300.top/weixinsell/pay/notify
  templateId:
    orderStatus: 3wdYrGyWvLK1tnjO7i1NP9OV_aLMHEJPw6rbBP5YL8k

#微信公众号的项目前缀url[微信公众平台授权,微信开发平台授权,项目域名]
projectUrl:
  wechatMpAuthorize: http://weixinsell.nat300.top
  wechatOpenAuthorize: http://weixinsell.nat300.top
  sell: http://weixinsell.com
